// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyArVjbGWFhai9MA05K_m95ssJHp0Gb9KM4',
    appId: '1:1087794398457:web:e670608d58a08455c80e28',
    messagingSenderId: '1087794398457',
    projectId: 'feedit-53d65',
    authDomain: 'feedit-53d65.firebaseapp.com',
    databaseURL: 'https://feedit-53d65-default-rtdb.firebaseio.com',
    storageBucket: 'feedit-53d65.appspot.com',
    measurementId: 'G-DL0S382JMK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC3ipqbOxYDc6ZPTVRS5EkPkcIyH7woCoE',
    appId: '1:1087794398457:android:bd7d09166a604df1c80e28',
    messagingSenderId: '1087794398457',
    projectId: 'feedit-53d65',
    databaseURL: 'https://feedit-53d65-default-rtdb.firebaseio.com',
    storageBucket: 'feedit-53d65.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDmFAh-bTizzkwD_IRIzLxRmdxaDhlE7V4',
    appId: '1:1087794398457:ios:31e708c65bd298e5c80e28',
    messagingSenderId: '1087794398457',
    projectId: 'feedit-53d65',
    databaseURL: 'https://feedit-53d65-default-rtdb.firebaseio.com',
    storageBucket: 'feedit-53d65.appspot.com',
    iosBundleId: 'com.example.flutterApplication3',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDmFAh-bTizzkwD_IRIzLxRmdxaDhlE7V4',
    appId: '1:1087794398457:ios:31e708c65bd298e5c80e28',
    messagingSenderId: '1087794398457',
    projectId: 'feedit-53d65',
    databaseURL: 'https://feedit-53d65-default-rtdb.firebaseio.com',
    storageBucket: 'feedit-53d65.appspot.com',
    iosBundleId: 'com.example.flutterApplication3',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyArVjbGWFhai9MA05K_m95ssJHp0Gb9KM4',
    appId: '1:1087794398457:web:e57c286d184698f8c80e28',
    messagingSenderId: '1087794398457',
    projectId: 'feedit-53d65',
    authDomain: 'feedit-53d65.firebaseapp.com',
    databaseURL: 'https://feedit-53d65-default-rtdb.firebaseio.com',
    storageBucket: 'feedit-53d65.appspot.com',
    measurementId: 'G-CREF6K02N2',
  );
}
